/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * User Roles Enum
 */
export enum UserRole {
  ADMIN = "Admin",
  WORKER = "Çalışan",
  GUEST = "Misafir"
}

/**
 * 1. Users Table Schema
 */
export interface User {
  id: string; // UUID
  username: string;
  passwordHash: string; // bcrypt hash
  fullName: string;
  role: UserRole;
  email: string;
  phoneNumber?: string;
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
  isActive: boolean;
}

/**
 * 2. Roles Table Schema
 */
export interface Role {
  id: string;
  name: UserRole;
  description: string;
  permissions: string[]; // List of permission codes e.g. "parcels:write", "finance:read"
}

/**
 * Crop Type Enum
 * Distinguishes olive orchards from other vegetable/fruit cultivation parcels,
 * allowing the existing Parcel/Tree infrastructure (observations, applications,
 * harvests, finance, AI recommendations) to be reused for non-olive crops.
 */
export type CropType = "Zeytin" | "Sebze" | "Meyve";

/**
 * 3. Parcels Table Schema (Mersin Toroslar / Değirmençay fields)
 */
export interface Parcel {
  id: string;
  name: string; // e.g. "Değirmençay Merkez Zeytinlik"
  cropType: CropType; // Ürün türü: Zeytin, Sebze veya Meyve
  latitude: number;
  longitude: number;
  areaDekar: number; // Alan bilgisi (Dekar)
  treeCount: number;
  soilType: string; // e.g. "Killi-Tınlı", "Kireçli"
  irrigationType: string; // e.g. "Damlama", "Yağmurlama", "Kuru"
  notes?: string;
  qrCodeData?: string; // Serialized link or token
  createdAt: string;
  updatedAt: string;
}

/**
 * 4. Trees Table Schema (Tree-by-tree tracking option)
 */
export interface Tree {
  id: string;
  parcelId: string; // Foreign Key to Parcels
  treeNumber: string; // e.g. "P1-T12"
  variety: string; // e.g. "Ayvalık", "Gemlik", "Sarıulak"
  plantingYear: number;
  latitude?: number;
  longitude?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * 5. Observations Table Schema (Gözlem Modülü)
 */
export interface Observation {
  id: string;
  parcelId: string; // Foreign Key to Parcels
  treeId?: string; // Optional Foreign Key to Trees
  observerId: string; // Foreign Key to Users
  observationDate: string; // Date
  notes: string;
  audioNotePath?: string; // Path to recorded audio note
  createdAt: string;
}

/**
 * 6. Photos Table Schema (Exif tracking, multi-image support)
 */
export interface Photo {
  id: string;
  observationId: string; // Foreign Key to Observations
  originalUrl: string; // Saved path
  thumbnailUrl: string; // Autogenerated 150x150 path
  latitude?: number; // GPS read from EXIF
  longitude?: number; // GPS read from EXIF
  takenAt?: string; // Captured date read from EXIF
  fileSize: number;
  createdAt: string;
}

/**
 * 7. Inventory Table Schema (Depo stok takibi)
 */
export interface InventoryItem {
  id: string;
  categoryId: string; // Foreign Key to InventoryCategories
  name: string; // e.g. "Hektaş Bakır Sülfat"
  brand?: string;
  sku?: string;
  stockQuantity: number;
  unit: string; // e.g. "Litre", "Kg", "Adet"
  minStockAlert: number; // Minimum stock warning threshold
  unitPrice: number; // Cost per unit (TL)
  expiryDate?: string;
  invoicePhotoUrl?: string;
  labelPhotoUrl?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * 8. InventoryCategories Table Schema
 */
export interface InventoryCategory {
  id: string;
  name: string; // e.g. "İlaç", "Gübre", "Biyolojik Ürün", "Alet"
  description?: string;
}

/**
 * 9. Fertilizers Table Schema (Nutrient tracking helper)
 */
export interface Fertilizer {
  id: string;
  inventoryItemId: string; // Foreign Key to InventoryItem
  npkRatio?: string; // e.g. "15-15-15"
  organicContentPercent?: number;
  microElements?: string; // e.g. "Bor, Çinko"
}

/**
 * 10. Chemicals Table Schema (Pesticides, fungicides)
 */
export interface Chemical {
  id: string;
  inventoryItemId: string; // Foreign Key to InventoryItem
  activeIngredient: string; // Etken madde
  targetPests: string[]; // e.g. ["Zeytin Sineği", "Halkalı Leke"]
  preHarvestIntervalDays: number; // Hasat öncesi bekleme süresi (PH)
}

/**
 * 11. Applications Table Schema (İlaçlama/Gübreleme Uygulama Geçmişi)
 */
export interface Application {
  id: string;
  parcelId: string; // Foreign Key to Parcels
  inventoryItemId: string; // Foreign Key to InventoryItem (Fertilizer or Chemical used)
  applicatorId: string; // Foreign Key to Users (Kim uyguladı)
  applicationDate: string;
  appliedDosage: number; // m2 or tree dosage
  dosageUnit: string; // e.g. "gr/Ağaç", "lt/Dekar"
  totalAmountUsed: number; // stock reduction
  weatherCondition?: string; // e.g. "Güneşli, Rüzgarsız"
  applicationNotes?: string;
  totalCost: number; // Calculated dynamically: totalAmountUsed * item.unitPrice
  createdAt: string;
}

/**
 * 12. Irrigation Table Schema (Sulama Geçmişi)
 */
export interface Irrigation {
  id: string;
  parcelId: string; // Foreign Key to Parcels
  irrigationDate: string;
  durationMinutes: number; // Süre
  waterVolumeLiters: number; // Su miktarı
  method: string; // e.g. "Damlama", "Salma"
  waterCost: number; // Su maliyeti
  notes?: string;
  createdAt: string;
}

/**
 * 13. Harvest Table Schema (Hasat Kayıtları)
 */
export interface Harvest {
  id: string;
  parcelId: string; // Foreign Key to Parcels
  harvestDate: string;
  quantityKg: number; // kg miktar
  qualityGrade: string; // e.g. "Sızmalık", "Sofralık", "Dip Zeytini"
  personnelCount: number; // Çalışan sayısı
  laborCost: number; // İşçilik maliyeti
  transportCost: number; // Nakliye maliyeti
  otherCosts: number; // Diğer masraflar
  totalCost: number; // Toplam hasat maliyeti
  notes?: string;
  createdAt: string;
}

/**
 * 14. Costs Table Schema (Genel Maliyetler / Giderler)
 */
export interface Cost {
  id: string;
  parcelId?: string; // Optional FK (Genel çiftlik maliyeti ise boş kalabilir)
  category: string; // e.g. "İlaçlama", "Gübreleme", "Sulama", "Yakıt", "Budama", "İşçilik", "Amortisman"
  amount: number; // TL
  costDate: string;
  description?: string;
  referenceId?: string; // Linked ID to Irrigation, Application, Harvest etc.
  createdAt: string;
}

/**
 * 15. Sales Table Schema (Gelirler)
 */
export interface Sale {
  id: string;
  harvestId?: string; // Optional reference to Harvest run
  saleDate: string;
  buyerName?: string; // e.g. "Mersin Tariş Zeytin Kooperatifi" or "Organik Sağlık Markası"
  productType: string; // e.g. "Zeytinyağı (Sızma)", "Sofralık Yeşil Zeytin"
  quantityKg: number;
  unitPrice: number; // TL/kg
  totalRevenue: number; // TL (quantityKg * unitPrice)
  notes?: string;
  isOrganikSaglikBrand: boolean; // "Organik Sağlık" markası altındaki ürünler için
  createdAt: string;
}

/**
 * 16. ProfitReports Table Schema (Performans ve Maliyet Analizleri)
 */
export interface ProfitReport {
  id: string;
  year: number;
  parcelId?: string; // If undefined, represents overall farm
  totalYieldKg: number;
  totalExpenses: number;
  totalRevenue: number;
  netProfit: number;
  roi: number; // Return on Investment %
  yieldPerTreeKg: number;
  costPerKg: number;
  createdAt: string;
}

/**
 * 17. WeatherHistory Table Schema
 */
export interface WeatherRecord {
  id: string;
  recordDate: string;
  tempMax: number;
  tempMin: number;
  humidity: number;
  windSpeed: number;
  precipitationMm: number;
  condition: string;
  hasFrostRisk: boolean;
  soilTemperature?: number;
  createdAt: string;
}

/**
 * 18. AITasks Table Schema (Yapay Zeka Zamanlı Görevler/Takipler)
 */
export interface AITask {
  id: string;
  taskType: string; // e.g. "Hastalık Analizi", "Dozaj Hesaplama", "Genel Değerlendirme"
  status: "Pending" | "Completed" | "Failed";
  promptTemplate: string;
  results?: string;
  executionDate: string;
  createdAt: string;
}

/**
 * 19. AIRecommendations Table Schema (Yapay Zeka Tavsiyeleri)
 */
export interface AIRecommendation {
  id: string;
  parcelId?: string;
  recommendationType: "Hastalık" | "Gübreleme" | "Sulama" | "Genel" | "Gelişim Analizi";
  content: string;
  confidenceScore: number; // AI Güven Skoru
  usedDocumentsCount: number;
  usedObservationsCount: number;
  usedWeatherCount: number;
  usedInventoryCount: number;
  createdDate: string;
}

/**
 * 20. UploadedDocuments Table Schema (RAG Doküman Havuzu)
 */
export interface UploadedDocument {
  id: string;
  fileName: string;
  fileType: string; // "pdf" | "docx" | "txt" | "md"
  fileSize: number;
  uploadedBy: string; // User ID
  uploadDate: string;
  summary?: string;
}

/**
 * 21. VectorChunks Table Schema (RAG Chunks & Embeddings)
 */
export interface VectorChunk {
  id: string;
  documentId: string; // Foreign Key to UploadedDocuments
  chunkIndex: number;
  content: string;
  embeddings: number[]; // JSON represented float array
}

/**
 * 22. Notifications Table Schema (Akıllı Bildirimler)
 */
export interface Notification {
  id: string;
  title: string;
  message: string;
  type: "Frost" | "Rain" | "LowStock" | "Task" | "System";
  isRead: boolean;
  targetRole?: UserRole; // Broadcast to role
  createdAt: string;
}

/**
 * 23. ActivityLogs Table Schema (Denetim & Güvenlik Takibi)
 */
export interface ActivityLog {
  id: string;
  userId: string; // Foreign Key to Users
  action: string; // e.g. "PARCEL_CREATE", "LOGIN_SUCCESS"
  details: string;
  ipAddress?: string;
  createdAt: string;
}

/**
 * 24. Settings Table Schema (Sistem Parametreleri)
 */
export interface SystemSetting {
  key: string; // e.g. "theme", "language", "backup_interval"
  value: string;
  updatedAt: string;
}

/**
 * Database Container Schema representing the full relational file database structure on disk.
 */
export interface DatabaseSchema {
  users: User[];
  roles: Role[];
  parcels: Parcel[];
  trees: Tree[];
  observations: Observation[];
  photos: Photo[];
  inventory: InventoryItem[];
  inventoryCategories: InventoryCategory[];
  fertilizers: Fertilizer[];
  chemicals: Chemical[];
  applications: Application[];
  irrigation: Irrigation[];
  harvest: Harvest[];
  costs: Cost[];
  sales: Sale[];
  profitReports: ProfitReport[];
  weatherHistory: WeatherRecord[];
  aiTasks: AITask[];
  aiRecommendations: AIRecommendation[];
  uploadedDocuments: UploadedDocument[];
  vectorChunks: VectorChunk[];
  notifications: Notification[];
  activityLogs: ActivityLog[];
  settings: SystemSetting[];
}
